apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragit-webapp-deployment
  labels:
    app: ragit-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragit-webapp
  template:
    metadata:
      labels:
        app: ragit-webapp
    spec:
      containers:
      - name: ragit-webapp
        image: rainmain/ragit-webapp:0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.digitalocean.com/load-balancer-name: "ragit-webapp"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "a9a9c392-c700-4e6f-a7e5-c392dce82d39"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
  name: ragit-webapp-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9080
  selector:
    app: ragit-webapp
  type: LoadBalancer
